### ISSUE TITLE
As to how to run NetTango locally...

### ISSUE THREAD

**Issue by eccstartup** [NetLogo/NetTango#18]
I wanted to leave a note [here](https://github.com/eccstartup/NetTangoInstall/blob/master/README-en.md).

**Comment by LaCuneta** [comment]
@eccstartup Nice, good idea.  I went ahead and added [some notes about this](https://github.com/NetLogo/NetTango/commit/4cc1d62cbe525b1990ade1248ef9136c153711fe) to the main NetTango `README.md` as well to better explain the process.
